### ISSUE TITLE
Make decrypt view a system overlay 

### ISSUE THREAD

**Issue by alepacheco** [Tiked/AndroRW#5]
This will make the decryption note stay on to of everything causing a partial DOS and I will look cool.
I will implemented myself when I have time, will use the issues panel to annotate new features to add.

Useful stuff:
- `windowManager = (WindowManager) getSystemService(WINDOW_SERVICE);`
- `<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />`

**Comment by joaopandolfi** [comment]
Nice!
